# Generated by Django 3.2.5 on 2021-10-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(blank=True, max_length=20, null=True)),
                ('problem_statement', models.CharField(blank=True, max_length=255, null=True)),
                ('Rules', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('parent_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(blank=True, max_length=20, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('media_path', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilp.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('level_name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('components', models.CharField(blank=True, max_length=255, null=True)),
                ('key_concept', models.CharField(blank=True, max_length=255, null=True)),
                ('key_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('kit', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilp.user')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilp.level'),
        ),
    ]
