# Generated by Django 3.2.5 on 2021-10-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='photo',
            field=models.ImageField(null=True, upload_to='challenge_image'),
        ),
        migrations.AddField(
            model_name='level',
            name='photo',
            field=models.ImageField(null=True, upload_to='level_image'),
        ),
    ]
