# Generated by Django 3.2.10 on 2022-01-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='challenge_image')),
                ('problem_statement', models.CharField(blank=True, max_length=255, null=True)),
                ('Rules', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gamephoto', models.ImageField(null=True, upload_to='game_image')),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('mode', models.CharField(blank=True, max_length=255, null=True)),
                ('age_group', models.CharField(blank=True, max_length=50, null=True)),
                ('emi', models.CharField(blank=True, max_length=255, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('key_concept', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('game_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('membership', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.TextField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('components', models.TextField(blank=True, null=True)),
                ('learning_projects', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_stem_kits', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(null=True)),
                ('level_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='level_image')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('components', models.CharField(blank=True, max_length=255, null=True)),
                ('key_concept', models.CharField(blank=True, max_length=255, null=True)),
                ('key_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='ilp3app.games')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(null=True, upload_to='student_image')),
                ('contact', models.CharField(blank=True, max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('parent_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ManyToManyField(to='ilp3app.Challenge')),
                ('game', models.ManyToManyField(to='ilp3app.Games')),
                ('level', models.ManyToManyField(to='ilp3app.Level')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='ilp3app.level'),
        ),
    ]
