# Generated by Django 3.2.10 on 2022-01-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilp3app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(blank=True, max_length=20, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('media_path', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='ilp3app.challenge')),
            ],
        ),
    ]
